# Configuración de Prometheus para N-Reinas Distribuido
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "nreinas-monitor"

# Configuración de reglas de alertas
rule_files:
  - "rules/*.yml"

# Configuración de scraping
scrape_configs:
  # Métricas de Prometheus mismo
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s
    metrics_path: "/metrics"

  # Aplicación N-Reinas
  - job_name: "nreinas-app"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    scrape_interval: 15s
    metrics_path: "/metrics"
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ["prometheus"]

  # Node Exporter (métricas del sistema)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]
    scrape_interval: 15s
    metrics_path: "/metrics"

  # cAdvisor (métricas de contenedores)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["host.docker.internal:8081"]
    scrape_interval: 15s
    metrics_path: "/metrics"

  # Grafana métricas
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    scrape_interval: 30s
    metrics_path: "/metrics"

# Configuración de AlertManager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
